= 2016-08-07

## 仕事
今週納期の細かい案件をやっつけ中。

あと、やるのかやらないのかよくわからん案件が結構重い作業になるので、やるのかやらないのかはやく決まってほしい。

## ゲーム
土曜に錦糸公園行ったらポケモンしてるひとがめちゃめちゃ多くてちょっと日本だいじょうぶかって感じになった。

とは言ってもぼくも待ち合わせの時間の30分くらい前に着いてポケモンやってましたが…

## いろいろ
土日まとめて。

8/6

ゴジラ観に錦糸町へ。

いつもは日本橋でTCXで観るんだけども、錦糸町にもTOHOあるって知ってじゃあ今回は近いし錦糸町でってことで行ってみた。

ふらっと行くには良いけど、ちゃんと観たいならやっぱ日本橋かなあと。IMAXとかで観るなら新宿とかになるんだけど、新宿こわいし遠いしあまり行きたくない…

でもIMAXすごいらしいので観てみたい気持ちはある！

で、ゴジラ。

ぶっちゃけて言えば映画としてはおもしろいの一言に尽きるわけだけども、子供の頃しかゴジラ観てなかった身分としては、ゴジラVS怪獣とか、ゴジラVS人間（いろんな武器）という、ゴジラと何かが戦う＝武力で勝つって感じで、それがこわいながらも楽しく観てたわけだけど。

現代？のゴジラはほぼ観てないのであれだけど、人間が知力で勝つみたいな感じになってて、たしかにまあ現代ならそうだよねって感じで多少の物足りなさを感じた。

内容としてはぶっちゃけ巨人兵をゴジラにしただけって感じではあるんだけど、巨人兵を初めてみたときの怖さと言ったら今思えば昔のゴジラを観た時の感じと近いというか、人間の力ではどうにもならなさ満載で、この場から過ぎ去ってくれない限り自分の身の安全は保証されない感じがすごかった。

特にバンカーバスター撃たれたあとに咆哮＋ブレス＋放射能みたいなとこはかんぜんに巨人兵のそれそのものだったけど、そうそうこれが怪獣映画でみたかったやつ！って感じですごいよかった。

あとは第二形態のウツボみたいなのもすごいよくて、キモさもさることながら、えっこれゴジラなの？って不安にさせるとこがすごいよかった。

ほんとこの2点だけで1800円払っ

次、BABYMETALのRIJ。

スーメタルが日本語で煽ったってみたんでどんなんかなと思って動画観たんですが…やばすぎじゃないですか？

「みんなの声を聞かせて」

「いっしょに歌ってくれる？」

ってまじでやばくないですか？

いつもは

「Let us hear your voice」

「Let's sing together!」

って言ってるのに日本語になるとこの破壊力はまじでやばすぎで、今日見に行ったひとたちすごいうらやましいなと。


8/7

近所の激安青果店で食材買ってきて久々にまともな作り置きを作った。

よく見てるリーマン投資家のブログで毎月の家計簿公開してて、資産いっぱい持ってるのに毎月の食費1万ちょいなんだけど、いったいどうやったらそうなるのかすごい不思議。

均等割しても週に約3000円なわけで、えっこれで大丈夫なんすかって感じで、ぼくの場合いくらがんばっても2万くらいなので、ぼくもこれめざしてがんばっていきたい。

まあビール（発泡酒）とかお惣菜とか買っちゃうってのはあるんだけど、それにしても1万はすごい。