= 2016-08-11

## 仕事
休みですんで…


## ゲーム
上野に用があったのでついでに上野公園行ってきたんだけど、もともとあそこひとが多いけど路肩に座ってる人がめちゃ多くて余裕でポケモンGOやってるのがわかる。

上野公園、何度か行ってるけど不忍池ってどこにあるのかまったくわからなかったけど、ポケモンGOやってたらでっかい池が表示されてたのでやっと存在を認識した。すぐそばにあったんですね…

## いろいろ
ちょっとそこそこでかい買い物（10万円くらい）しようと思っている。

それにともなってってわけじゃないんだけど、友達もいないんで交際費でお金使うこともほとんどないんでお金自体基本的に食費（三食＋コンビニとかで買ったりしたやつを勘定科目として食費でまとめてる）と日用品とあとたまになんか欲しくなったら買う程度しか使ってない。

一人暮らし始めてから基本的にものをあまり買わなくなって、理由としては部屋がそんなに広くないというのと、買ったものに対して元が取れてるか（費用対効果）をすごく考えるようになった。

なのでもともとそんなお金持ってないけど、最近特にお金を使いたくないというかなるべく使わないようになった。

食費もほんとは月1万くらいにしたいんだけど、まずもって無理なのが週2.5kしか使わないというのが無理で、いやできないことはないかもしれないけど、一日中外に出ないで自炊するとか、一食必ず豆腐ともやしだけにするとか、そういう極端なことしないとまず無理。

そもそも、自炊で安くなるかというとそうでもなくて、例えば

* 鶏胸肉1kg 700円
* きゅうり 150円
* なす 150円
* とまと 200円
* 納豆 100円（3パック）
* 豆腐 100円（3パック）
* たまご 200円
* もやし 100円（3袋）

基本としてこれ買ったとしてこの時点で1700円。あとビール（発泡酒）とかコーヒーとかパンとか買っちゃうと2500円とかすぐいっちゃう。

（まあビールとか買ってんじゃねーよとか、食パン以外のパン買ってんじゃねーよとかあると思いますが…）

この食材で3食作れますかって言われたらもう無理じゃん？

食材選びがすでにあれなのはわかってるけど、毎日定時で帰れるわけじゃないんで作りおきしてても期日まで食べられないこともあるし、そうなると作ったら冷凍しなくちゃならないし、冷凍するには冷凍できる食材で作らなくちゃならないし、とかいろいろ考えることあってめんどくさい。

2500 / 7 = 357

357 / 3 = 119

一食100円とか無理じゃないっすか…

まあ別に食費2万でも2倍になるだけなんで一食200円ちょいなわけで、これはリーマン的にはほぼ無理ということになりますね。

食費はまあともかく、とりあえず買いたいものはいろいろあるけど、まず買ったとしてこれをそもそも何回使いそうかというのを考え、それを価格で割って時間単価を求め、それに納得できたら買うみたいな感じになってる。

なので、ゲームなんかは買うのは良いけどまずもってクリアまでできないし、7000円くらいだしてもおそらく10回起動するかどうか。そうなると1回700円。700円あったら漫画でも買ったほうが良いなあ。でも漫画も1回しかみないしなあ。別に漫画観たところで誰に話すわけでもないんでみなきゃみないで別にいいし、どうしてもみたいならゲオればいいし。

みたいな感じになって結局買わないというのが多い。

今月は後輩と映画観に行ったりそのついでに飲み会2回したりしてすでに交際費で1万くらい使ってて、人に会うのは必要なのでまあこれはいいとして、その分どっかで削らないとなあとか考えてます。

とりあえずなにも考えず普通の生活してても貯金はそれなりにできるし窮困してるわけでもないんだけど、引っ越して家賃が15k上がったのが結構プレッシャーになってて、どっかでその15kを取り戻したいと考えてるのかもしれない。